### ISSUE TITLE
Polling frequency

### ISSUE THREAD

**Issue by mnot** [recoilme/rss2tg#1]
The client at 37.35.107.66 identifies itself as rss2tg, and is polling my feed about every five minutes. If it continues, I'll be blocking the IP, and I suspect other admins will react similarly.

**Comment by recoilme** [comment]
Hello, sorry for late response, I'm on vacation..
What's your feed name? I use library github.com/SlyMarbo/rss it must respect polling frequency if rss feed has it in settings:

"The library does its best to follow the appropriate specifications and not to set the Refresh time too soon. It currently follows all update time management methods in the RSS 1.0, 2.0, and Atom 1.0 specifications. If one is not provided, it defaults to 10 minute intervals."

**Comment by mnot** [comment]
Thanks, I've raised https://github.com/SlyMarbo/rss/issues/81

**Comment by recoilme** [comment]
Thanks, great point
